---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.eclipse.org/git-commit: 51cd0f6e4bacf365a05144a06661038f1e1040b0
      jkube.eclipse.org/git-url: git@github.com:homeclickfinance/Code_Library.git
      jkube.eclipse.org/git-branch: main
    labels:
      app: DockerVKubernate
      provider: jkube
      version: 1.0-SNAPSHOT
      group: com.mycompany
    name: dockervkubernate
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: DockerVKubernate
      provider: jkube
      group: com.mycompany
    type: NodePort
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      jkube.eclipse.org/git-commit: 51cd0f6e4bacf365a05144a06661038f1e1040b0
      jkube.eclipse.org/git-url: git@github.com:homeclickfinance/Code_Library.git
      jkube.eclipse.org/git-branch: main
    labels:
      app: DockerVKubernate
      provider: jkube
      version: 1.0-SNAPSHOT
      group: com.mycompany
    name: dockervkubernate
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: DockerVKubernate
        provider: jkube
        group: com.mycompany
    template:
      metadata:
        annotations:
          jkube.eclipse.org/git-commit: 51cd0f6e4bacf365a05144a06661038f1e1040b0
          jkube.eclipse.org/git-url: git@github.com:homeclickfinance/Code_Library.git
          jkube.eclipse.org/git-branch: main
        labels:
          app: DockerVKubernate
          provider: jkube
          version: 1.0-SNAPSHOT
          group: com.mycompany
        name: dockervkubernate
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: mycompany/dockervkubernate:latest
          imagePullPolicy: IfNotPresent
          name: webapp
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          securityContext:
            privileged: false
