/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package jframe.nforjapp;


import java.awt.Dimension;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import logins.sqls.LoginEntilysql;
import user.log.autenti.Tradeloginusers;

/**
 *
 * @author homec
 */

public class NforJAPP extends javax.swing.JFrame { 
    


    public NforJAPP() {
        initComponents();
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold> 
    
 public static void main(String[] args) {
        // Retrieve user information from the database
        List<Tradeloginusers> tradeloginusers = new LoginEntilysql().getlists();

        // Create and configure the login form
        SwingUtilities.invokeLater(() -> {
            JFrame loginFrame = new JFrame("Login Form");
            loginFrame.setSize(3000, 3000);
            loginFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            // Components for the login form
            JLabel usernameLabel = new JLabel("Username:");
            JTextField usernameField = new JTextField();
            JLabel passwordLabel = new JLabel("Password:");
            JPasswordField passwordField = new JPasswordField();
            JButton loginButton = new JButton("Login");
            
                    // Set preferred size for text fields
           
           
           passwordLabel.setPreferredSize(new Dimension(200, 250));
           passwordField.setPreferredSize(new Dimension(200, 250));
           usernameField.setPreferredSize(new Dimension(200, 250));
           usernameLabel.setPreferredSize(new Dimension(200, 250));
           loginButton.setPreferredSize(new Dimension(800, 100));





            // Layout configuration (you can use different layout managers as needed)

            // Add components to the frame
            loginFrame.add(usernameLabel);
            loginFrame.add(usernameField);
            loginFrame.add(passwordLabel);
            loginFrame.add(passwordField);
            loginFrame.add(loginButton);

            // ActionListener for the login button
            loginButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Get entered credentials
                    String enteredUsername = usernameField.getText();
                    char[] enteredPasswordChars = passwordField.getPassword();
                    String enteredPassword = new String(enteredPasswordChars);

                    // Check authentication
                    boolean authenticated = false;
                    for (Tradeloginusers user : tradeloginusers) {
                        if (user.getUsername().equals(enteredUsername) && user.getPasswords().equals(enteredPassword)) {
                            authenticated = true;
                            break;
                        }
                    }

                    // Display result
                    if (authenticated) {
                        // Authentication successful, open the NforJAPP JFrame
                        JFrame frame = new NforJAPPFrame();
                        frame.setVisible(true);
                        loginFrame.dispose(); // Close the login form
                    } else {
                        // Authentication failed, show a message
                        JOptionPane.showMessageDialog(loginFrame, "Authentication failed");
                    }

                    // Clear the password field for security
                    passwordField.setText("");
                }
            });

            // Set layout and make the frame visible
            // (you may need to adjust layout and appearance according to your design)
            loginFrame.setLayout(new BoxLayout(loginFrame.getContentPane(), BoxLayout.Y_AXIS)); // Y_AXIS for a vertical layout
            loginFrame.setVisible(true);
        });
    }
 
    
}


    
/*    
public static void main(String[] args) {
    
        List<Tradeloginusers> tradeloginusers = new LoginEntilysql().getlists();
       
        // Replace the following lines with your actual login logic
        String enteredUsername = "andrew1"; // Replace with user input
        String enteredPassword = "first1"; // Replace with user input

        boolean authenticated = false;
        for (Tradeloginusers user : tradeloginusers) {
             System.out.println(user.displaytradeloginusers());
             if (user.getUsername().equals(enteredUsername) && user.getPasswords().equals(enteredPassword)) {
             authenticated = true;
             break;
            }
        }
     

        if (authenticated) {
            // Authentication successful, open the NforJAPP JFrame
            SwingUtilities.invokeLater(() -> {
                JFrame frame = new NforJAPPFrame();
                frame.setVisible(true);
            });
        } else {
            // Authentication failed, handle accordingly
            System.out.println("Authentication failed");
            System.out.println("Entered Username: " + enteredUsername);
            System.out.println("Entered Password: " + enteredPassword);
        }
    }
}
*/